export const FETCH_DETAIL_COURCE = "FETCH_DETAIL_COURCE";
export const FETCH_COURSE = "FETCH_COURSE";
export const GET_USER_LOGIN = "GET_USER_LOGIN";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_COURSE_LIST_BY_CATEGORY = "FETCH_COURSE_LIST_BY_CATEGORY";
export const FETCH_COURSE_LIST = "FETCH_COURSE_LIST";
export const FETCH_COURSE_LIST_BY_CATEGORY_DEFAULT = "FETCH_COURSE_LIST_BY_CATEGORY_DEFAULT";
export const FETCH_COURSE_LIST_PER_PAGE = "FETCH_COURSE_LIST_PER_PAGE";
export const FETCH_MA_LOAI_NGUOI_DUNG = "FETCH_MA_LOAI_NGUOI_DUNG";

export const FETCH_COURSE_LIST_SAME_CATEGORY = "FETCH_COURSE_LIST_SAME_CATEGORY";

export const GET_USER_INFO = "GET_USER_INFO";
export const FETCH_SEARCH_COURSE = "FETCH_SEARCH_COURSE";
export const UPDATE_COURSE = "UPDATECOURSE";
export const GET_COURSE_REGISTED = "GET_COURSE_REGISTED";
export const GET_USER_HEADERS = "GET_USER_HEADERS";
