export const FETCH_DETAIL_COURCE = "FETCH_DETAIL_COURCE";
export const FETCH_COURSE = "FETCH_COURSE";
export const GET_USER_LOGIN = "GET_USER_LOGIN";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_COURSE_LIST_BY_CATEGORY = "FETCH_COURSE_LIST_BY_CATEGORY";
export const FETCH_COURSE_LIST = "FETCH_COURSE_LIST";
export const FETCH_COURSE_LIST_BY_CATEGORY_DEFAULT = "FETCH_COURSE_LIST_BY_CATEGORY_DEFAULT";
export const FETCH_COURSE_LIST_PER_PAGE = "FETCH_COURSE_LIST_PER_PAGE";
export const FETCH_MA_LOAI_NGUOI_DUNG = "FETCH_MA_LOAI_NGUOI_DUNG";
export const FETCH_ALL_COURSE_BY_ADMIN = "FETCH_ALL_COURSE_BY_ADMIN";
export const FETCH_SEARCH_COURSES = "FETCH_SEARCH_COURSES";

export const FETCH_COURSE_LIST_SAME_CATEGORY = "FETCH_COURSE_LIST_SAME_CATEGORY";

export const GET_USER_INFO = "GET_USER_INFO";
export const FETCH_SEARCH_COURSE = "FETCH_SEARCH_COURSE";
export const UPDATE_COURSE = "UPDATECOURSE";
export const GET_COURSE_REGISTED = "GET_COURSE_REGISTED";
export const GET_USER_HEADERS = "GET_USER_HEADERS";

export const FETCH_USER_LIST_PER_PAGE = "FETCH_USER_LIST_PER_PAGE";
export const FETCH_USER_LIST_PER_PAGE_DATA = "FETCH_USER_LIST_PER_PAGE_DATA";

export const DELETE_USER_BY_ADMIN = "DELETE_USER_BY_ADMINN";

export const UPDATE_USER_BY_ADMIN = "UPDATE_USER_BY_ADMINN";
export const UPDATE_USER_BY_USER = "UPDATE_USER_BY_USER";

export const GET_ALL_USER_BY_ADMIN = "GET_ALL_USER_BY_ADMIN";
export const GET_DATA_USER_BY_ADMIN = "GET_DATA_USER_BY_ADMIN";
export const FETCH_COURSE_LIST_PER_PAGE_ADMIN = "FETCH_COURSE_LIST_PER_PAGE_ADMIN";
export const ADD_NEW_COURSE_BY_ADMIN = "ADD_NEW_COURSE_BY_ADMIN";
export const DELETE_COURSE_BY_ADMIN = "DELETE_COURSE_BY_ADMIN";
export const EDIT_COURSE_DETAIL_BY_ADMIN = "EDIT_COURSE_DETAIL_BY_ADMIN";
